"""
SenseCritiq — Report generation service.
Renders synthesis data into Markdown or PDF reports.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER

REPORTS_DIR = Path(__file__).parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def render_markdown(session_id: str, session_name: str, data: dict) -> str:
    themes = data.get("themes", [])
    quotes = data.get("quotes", [])
    findings = data.get("findings", [])
    participant_count = data.get("participant_count", 0)
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y")

    lines = []
    lines.append(f"# {session_name}")
    lines.append(f"**Generated:** {generated_at}  ")
    lines.append(f"**Session ID:** `{session_id}`  ")
    lines.append(f"**Participants:** {participant_count}  ")
    lines.append(f"**Quotes captured:** {len(quotes)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Themes")
    lines.append("")
    for i, theme in enumerate(themes, 1):
        label = theme.get("label", f"Theme {i}")
        description = theme.get("description", "")
        severity = theme.get("severity", "")
        icon = {"high": "🔴", "medium": "🟡", "positive": "🟢"}.get(severity, "⚪")
        lines.append(f"### {icon} {label}")
        if description:
            lines.append(description)
        lines.append("")

    if findings:
        lines.append("## Key Findings")
        lines.append("")
        for i, finding in enumerate(findings, 1):
            text = finding.get("finding", finding.get("text", ""))
            sq = finding.get("supporting_quote", {})
            lines.append(f"**{i}. {text}**")
            if sq:
                quote_text = sq.get("text", sq.get("quote", ""))
                speaker = sq.get("speaker", "")
                timestamp = sq.get("timestamp", "")
                if quote_text:
                    lines.append("")
                    lines.append(f"> \"{quote_text}\"")
                    attribution = " — ".join(filter(None, [speaker, timestamp]))
                    if attribution:
                        lines.append(f"> *{attribution}*")
            lines.append("")

    if quotes:
        lines.append("## Verbatim Quotes")
        lines.append("")
        theme_groups = {}
        for q in quotes:
            t = q.get("theme", "Other")
            theme_groups.setdefault(t, []).append(q)
        for theme_label, tq in theme_groups.items():
            lines.append(f"### {theme_label}")
            lines.append("")
            for q in tq:
                text = q.get("text", q.get("quote", ""))
                speaker = q.get("speaker", "")
                timestamp = q.get("timestamp", "")
                lines.append(f"> \"{text}\"")
                attribution = " — ".join(filter(None, [speaker, timestamp]))
                if attribution:
                    lines.append(f"> *{attribution}*")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by SenseCritiq — sensecritiq.com*")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF renderer
# ---------------------------------------------------------------------------

def render_pdf(session_id: str, session_name: str, data: dict) -> Path:
    themes = data.get("themes", [])
    quotes = data.get("quotes", [])
    findings = data.get("findings", [])
    participant_count = data.get("participant_count", 0)
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y")

    path = REPORTS_DIR / f"{session_id}.pdf"

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=20*mm,
        rightMargin=20*mm,
        topMargin=20*mm,
        bottomMargin=20*mm,
    )

    base = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("SCTitle", parent=base["Title"],
        fontSize=22, textColor=colors.HexColor("#1A202C"), spaceAfter=4)
    meta_style = ParagraphStyle("SCMeta", parent=base["Normal"],
        fontSize=9, textColor=colors.HexColor("#718096"), spaceAfter=2)
    h2_style = ParagraphStyle("SCH2", parent=base["Heading2"],
        fontSize=14, textColor=colors.HexColor("#2D3748"),
        spaceBefore=14, spaceAfter=6)
    h3_style = ParagraphStyle("SCH3", parent=base["Heading3"],
        fontSize=11, textColor=colors.HexColor("#2D3748"),
        spaceBefore=8, spaceAfter=4)
    body_style = ParagraphStyle("SCBody", parent=base["Normal"],
        fontSize=10, textColor=colors.HexColor("#4A5568"),
        leading=15, spaceAfter=6)
    quote_style = ParagraphStyle("SCQuote", parent=base["Normal"],
        fontSize=10, textColor=colors.HexColor("#2D3748"),
        leftIndent=12, leading=15,
        borderColor=colors.HexColor("#E2E8F0"),
        borderWidth=2, borderPad=8,
        backColor=colors.HexColor("#F7FAFC"),
        spaceAfter=4)
    attribution_style = ParagraphStyle("SCAttrib", parent=base["Normal"],
        fontSize=9, textColor=colors.HexColor("#718096"),
        leftIndent=12, spaceAfter=10)
    finding_style = ParagraphStyle("SCFinding", parent=base["Normal"],
        fontSize=10, textColor=colors.HexColor("#1A202C"),
        leading=15, spaceBefore=6, spaceAfter=4,
        fontName="Helvetica-Bold")
    footer_style = ParagraphStyle("SCFooter", parent=base["Normal"],
        fontSize=8, textColor=colors.HexColor("#A0AEC0"),
        alignment=TA_CENTER)

    # Header
    story.append(Paragraph(session_name, title_style))
    story.append(Paragraph(
        f"Generated {generated_at} &nbsp;|&nbsp; {participant_count} participant(s) &nbsp;|&nbsp; {len(quotes)} quotes",
        meta_style
    ))
    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 4*mm))

    # Themes
    story.append(Paragraph("Themes", h2_style))
    for theme in themes:
        label = theme.get("label", "")
        description = theme.get("description", "")
        severity = theme.get("severity", "")
        color_map = {"high": "#E53E3E", "medium": "#D69E2E", "positive": "#38A169", "low": "#38A169"}
        dot_color = color_map.get(severity, "#A0AEC0")
        story.append(Paragraph(f'<font color="{dot_color}">&#9679;</font> <b>{label}</b>', h3_style))
        if description:
            story.append(Paragraph(description, body_style))

    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))

    # Key Findings
    if findings:
        story.append(Paragraph("Key Findings", h2_style))
        for i, finding in enumerate(findings, 1):
            text = finding.get("finding", finding.get("text", ""))
            sq = finding.get("supporting_quote", {})
            story.append(Paragraph(f"{i}. {text}", finding_style))
            if sq:
                quote_text = sq.get("text", sq.get("quote", ""))
                speaker = sq.get("speaker", "")
                timestamp = sq.get("timestamp", "")
                if quote_text:
                    story.append(Paragraph(f'"{quote_text}"', quote_style))
                    attribution = " — ".join(filter(None, [speaker, timestamp]))
                    if attribution:
                        story.append(Paragraph(attribution, attribution_style))

        story.append(Spacer(1, 4*mm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))

    # Verbatim Quotes
    if quotes:
        story.append(Paragraph("Verbatim Quotes", h2_style))
        theme_groups = {}
        for q in quotes:
            t = q.get("theme", "Other")
            theme_groups.setdefault(t, []).append(q)
        for theme_label, tq in theme_groups.items():
            story.append(Paragraph(theme_label, h3_style))
            for q in tq:
                text = q.get("text", q.get("quote", ""))
                speaker = q.get("speaker", "")
                timestamp = q.get("timestamp", "")
                story.append(Paragraph(f'"{text}"', quote_style))
                attribution = " — ".join(filter(None, [speaker, timestamp]))
                if attribution:
                    story.append(Paragraph(attribution, attribution_style))

    # Footer
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 2*mm))
    story.append(Paragraph("Generated by SenseCritiq — sensecritiq.com", footer_style))

    doc.build(story)
    return path


# ---------------------------------------------------------------------------
# Save helper
# ---------------------------------------------------------------------------

def save_report(session_id: str, content: str, fmt: str = "markdown") -> Path:
    ext = "md" if fmt == "markdown" else fmt
    path = REPORTS_DIR / f"{session_id}.{ext}"
    path.write_text(content, encoding="utf-8")
    return path
